site_name: Python Computer Vision
theme:
    name: 'material'
    palette:
        primary: 'black'

nav:
    - Introduction: index.md
    - Image Basics: basics.md
    - Videos: videos.md
    - Installation: install.md

repo_name: mapattacker/computer-vision-python
repo_url: https://github.com/mapattacker/computer-vision-python

markdown_extensions:
    - codehilite